name: AceTheGame CI
on: [push]

jobs:
  ACE:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: "install compiler and build tools"
        run: sudo apt-get install build-essential

      - name: create build directory
        working-directory: ./ACE
        run: mkdir build

      # debug
      - name: debug build
        working-directory: ./ACE/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug ../
          make -j${nproc}

      - name: debug unit test
        working-directory: ./ACE/build
        run: ./test/test_ace -s

      # release
      - name: release build
        working-directory: ./ACE/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release ../ 
          make -j${nproc}

      - name: release unit test
        working-directory: ./ACE/build
        run: ./test/test_ace -s

  Modder:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: "install build dependecies"
        run: sudo apt-get install openjdk-17-jdk-headless apktool gradle

      - name: generating code for injection
        working-directory: ./Modder/injector
        run: python3 ./gen_smali.py

      - name: build
        working-directory: ./Modder
        # only build no testing
        run: ./gradlew build -x test

      - name: test
        working-directory: ./Modder
        # only build no testing
        run: ./gradlew test
